### ISSUE TITLE
Sveitarfélag = Útlönd?

### ISSUE THREAD

**Issue by einarjon** [busla/flottafolktilislands-ui#1]
Hvap með íslendinga erlendis? 
Þeir vilja kannski styrkja, þó að þeir geti ekki hýst.
Legg til að bæta við 'Útlönd' aftast í MUNICIPALITIES (verður að gerast eftir sort() kallið)

diff --git a/dist/scripts/app.js b/dist/scripts/app.js
index e9e3659..d2c9b2d 100644
--- a/dist/scripts/app.js
+++ b/dist/scripts/app.js
@@ -657,6 +657,7 @@ var App = React.createClass({
 });

 var MUNICIPALITIES = ['Sveitarfélag', 'Hafnarfjörður', 'Garðabær', 'Álftanes', 'Kópavogur', 'Reykjavík', 'Seltjarnarnes', 'Mosfellsbær', 'Mosfellsdal', 'Kjalarnes', 'Grindavík', 'Hafnir', 'Sandgerði'
+MUNICIPALITIES.append('Útlönd'); // er þetta löglegt JS?

 React.render(React.createElement(App, { url: 'http://45.79.178.154:1337' }), document.getElementById('app'));

**Comment by busla** [comment]
```
var MUNICIPALITIES = [.....].sort();
MUNICIPALITIES.push('Útlönd');
```

:+1:
